# Generated by Django 4.1.7 on 2023-04-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_webpage_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpage",
            name="email",
            field=models.EmailField(default="akhif@gmail.com", max_length=254),
        ),
    ]
